name = 'RLC theme'
license = 'MIT'
licenselink = 'https://github.com/owner/repo/LICENSE'
description = 'Theme for rlc.edu.hk'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/owner/repo'

# If you have a running demo of the theme
demosite = 'https://rlc.edu.hk/'

# Taxonomy terms
tags = ['company']
features = ['Responsive design']

# If the theme has a single author
[author]
  name = 'Jonah'
  homepage = 'https://github.com/alexeyismirnov'

